sign-commit = true
sign-tag = true
consolidate-commits = true
tag-name = "v{{version}}"
tag-message = "{{tag_name}}"
pre-release-hook = ["cargo", "hack"]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"},
]
