[package]
name = "async-graphql-example"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
async-graphql = "2.4.6"
entity = { version = "0.2.0", path = "../../entity", features = ["async-graphql", "global", "inmemory_db", "macros"] }
futures = "0.3.9"
serde_json = "1.0"
