name: Semver

on:
  push:

env:
  RUST_BACKTRACE: 1

jobs:
  semver:
    name: Check semver for ${{ matrix.crate }} crate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [entity, entity_macros, entity_noop_macros]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-19
          override: true
          components: rustc-dev, llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - name: Install rust-semverver
        run: cargo install --git https://github.com/rust-lang/rust-semverver --rev 71c340ff867d2f79613cfe02c6714f1d2ef00bc4
      - run: cd "${{ matrix.crate }}" && cargo semver --api-guidelines --all-features
