name: Semver

on:
  push:
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  install-semver:
    name: Install the semver tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-19
          override: true
          components: rustc-dev llvm-tools-preview
      - name: Install rust-semverver
        run: cargo install --git https://github.com/rust-lang/rust-semverver --rev 71c340ff867d2f79613cfe02c6714f1d2ef00bc4
  check-entity:
    name: Check entity crate (all features)
    runs-on: ubuntu-latest
    steps:
      - needs: install-semver
      - run: cd entity && cargo semver --api-guidelines --all-features
  check-entity-macros:
    name: Check entity_macros crate (all features)
    runs-on: ubuntu-latest
    steps:
      - needs: install-semver
      - run: cd entity_macros && cargo semver --api-guidelines --all-features
  check-entity-noop-macros:
    name: Check entity_macros crate (all features)
    runs-on: ubuntu-latest
    steps:
      - needs: install-semver
      - run: cd entity_noop_macros && cargo semver --api-guidelines --all-features
